version: '3.11'
services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      POSTGRES_DB: Backend
      POSTGRES_USER: Backend_user
      POSTGRES_PASSWORD: "sajadfallahdoost1234"